name: Verify
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linters
        run: |
          bin/rubocop --parallel

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup PostgreSQL
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14
          database: lynch_creek_corporate_test

      - name: Setup the application
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bin/rails assets:precompile

      - name: Run all tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
          PARALLEL_WORKERS=1 bin/rails test:system
